"""Chart color scheme and Plotly template for all dashboards.

Built on the HWS brand standards (purple #510C76, green #006937, orange
#F26724 — see the toolkit at hws.edu/offices/communications/brand-standards).
Chart slots use brand-derived steps rather than the raw Pantone values where
those fall outside the legible lightness band: HWS purple at L=0.34 is too dark
to read as a mark, so the categorical purple is a tint of it.

Keep this file in sync with `.streamlit/config.toml` ([theme] chart* keys),
which paints Streamlit's native charts and the app chrome with the same steps.

The categorical palette is validated (lightness band, chroma floor, adjacent-pair
CVD separation, normal-vision floor, surface contrast). Adjacent pairs pass; all
pairs do not, so for scatter/bubble charts where every pair of colors can
collide, cap series at the first four slots (CATEGORICAL[:4]) or fold extras
into "Other". Gold and pink fall below 3:1 against the surface — give them
direct labels or a table view rather than relying on the fill alone.
"""
from __future__ import annotations

import plotly.graph_objects as go
import plotly.io as pio

# --- Categorical palette (identity), fixed order — never cycle past 8 ---
CATEGORICAL = [
    "#7a2da9",  # purple  — HWS purple, chart-legible tint
    "#006937",  # green   — HWS green (Pantone 349 C)
    "#f26724",  # orange  — HWS orange (Pantone 165 C)
    "#009e98",  # teal
    "#2d74ca",  # blue
    "#e7729b",  # pink
    "#cfaf1d",  # gold
    "#c2272d",  # crimson
]

# Sequential (magnitude): single hue — HWS green, light -> dark.
# Generated by hue-rotating the former purple ramp in OKLCH (hue 309 -> 154) so
# the lightness steps are unchanged, then gamut-clamping chroma. The light end is
# nudged one step darker than a pure rotation to clear 2:1 on the surface.
# Validated: lightness strictly monotonic, ends 2.0:1 and 10.2:1 on SURFACE.
SEQUENTIAL = [
    "#7ec495", "#57b97b", "#19a75d", "#008f4d", "#00783f", "#006032", "#004a25",
]

# Diverging (polarity): HWS orange <- neutral gray -> HWS green.
# The cool arm moved from purple to green so polarity reads with the brand's
# primary (and so growth is green). Poles pass CVD at ΔE 10.7 protan / 33.0
# normal — clear of the >=8 target, though a wider margin than the former
# purple pole's 30.7, so keep the +/- labels these bars already carry.
DIVERGING = [
    "#f26724", "#fd9a73", "#ffc9b3", "#e8e8e6", "#bce3c7", "#84ca9a", "#006d39",
]

# Recessive neutrals for marks that must be present but not compete: peer dots
# behind a highlighted institution, unshaded reference marks. Not a categorical
# slot — they carry no identity. Both are the former purple-cast grays rotated to
# the brand's green hue at unchanged lightness.
NEUTRAL_MARK = "#afb9b1"        # on the plot surface
NEUTRAL_MARK_STRONG = "#607065"  # over shaded/choropleth fills (5.1:1)

# Status colors — reserved for state, never used as "series N".
# Deliberately stepped off the categorical hexes so a status mark never reads
# as a series; pair them with an icon or label, never color alone.
STATUS = {
    "good": "#0f7a45",
    "warning": "#b8961a",
    "serious": "#d95d17",
    "critical": "#a81f26",
}

# Brand primaries, unmodified — for logos, rules, section accents, KPI ink.
BRAND = {
    "purple": "#510c76",  # Pantone 2607 C
    "green": "#006937",   # Pantone 349 C
    "orange": "#f26724",  # Pantone 165 C
}

# Text / surface tokens — match .streamlit/config.toml
SURFACE = "#fcfcfb"
SURFACE_ALT = "#e7f3ea"  # green tint 10%
# Orange tint 10% — same OKLCH lightness/chroma as SURFACE_ALT, rotated to the
# brand's orange hue, so a caution surface sits at the same visual weight as the
# ordinary card surface instead of shouting.
SURFACE_WARN = "#faece6"
# Solid fills for the deck callouts, which carry white body text. Green passes
# on the brand hue as-is (6.8:1), but Pantone 165 orange under white is only
# 3.1:1 — below the 4.5:1 floor — so the caveat fill is that hue darkened in
# OKLCH until it clears (4.9:1). Both are fills behind text, never chart ink.
CALLOUT_FILL = {"takeaway": BRAND["green"], "caveat": "#c04d12"}
ON_ACCENT = "#ffffff"  # text over any CALLOUT_FILL

TEXT_PRIMARY = "#0e1b12"
TEXT_SECONDARY = "#52514e"
GRID = "#cde1d2"  # green tint 20%

# Cera Pro per brand standards, Helvetica as the toolkit's named substitute.
FONT_FAMILY = "Cera Pro, Helvetica Neue, Helvetica, Arial, sans-serif"
# Display face — headlines, titles and graphic callouts (e.g. deck factoid
# numbers). Per the brand standards it is never used for body copy, and it ships
# in Bold (700) and Black (900) only, so anything lighter falls back to Cera Pro.
DISPLAY_FONT_FAMILY = "Cera Stencil Pro, Cera Pro, Helvetica Neue, Helvetica, Arial, sans-serif"

TEMPLATE_NAME = "hws"


def _scale(steps: list[str]) -> list[tuple[float, str]]:
    """Even (offset, color) stops for a Plotly continuous colorscale."""
    last = len(steps) - 1
    return [(i / last, c) for i, c in enumerate(steps)]


def register_template() -> None:
    """Register and activate the shared Plotly template. Idempotent."""
    pio.templates[TEMPLATE_NAME] = go.layout.Template(
        layout=dict(
            colorway=CATEGORICAL,
            font=dict(family=FONT_FAMILY, color=TEXT_PRIMARY, size=13),
            title=dict(font=dict(family=FONT_FAMILY, size=18, color=TEXT_PRIMARY)),
            paper_bgcolor=SURFACE,
            plot_bgcolor=SURFACE,
            # Plotly would space a plain color list evenly by itself; the stops
            # are written out so the mapping is visible at the call site.
            # `sequentialminus` is the one that matters here — left unset, a
            # continuous trace over a negative domain falls back to Plotly's
            # own scale instead of the brand ramp.
            colorscale=dict(
                sequential=_scale(SEQUENTIAL),
                sequentialminus=_scale(SEQUENTIAL),
                diverging=_scale(DIVERGING),
            ),
            # Axis text inherits layout.font.family, but the color and tick
            # furniture do not — set them so ticks never fall back to Plotly ink.
            xaxis=dict(gridcolor=GRID, zerolinecolor=GRID, ticks="outside",
                       tickcolor=GRID, linecolor=GRID,
                       tickfont=dict(family=FONT_FAMILY, color=TEXT_SECONDARY),
                       title=dict(font=dict(family=FONT_FAMILY,
                                            color=TEXT_SECONDARY))),
            yaxis=dict(gridcolor=GRID, zerolinecolor=GRID, ticks="outside",
                       tickcolor=GRID, linecolor=GRID,
                       tickfont=dict(family=FONT_FAMILY, color=TEXT_SECONDARY),
                       title=dict(font=dict(family=FONT_FAMILY,
                                            color=TEXT_SECONDARY))),
            legend=dict(orientation="h", yanchor="bottom", y=1.02,
                        xanchor="left", x=0,
                        font=dict(family=FONT_FAMILY, color=TEXT_PRIMARY)),
            # Hover is the one text layer Plotly styles from the trace color
            # rather than layout.font, so it needs saying explicitly — otherwise
            # tooltips ship in Plotly's default type on a white box.
            hoverlabel=dict(font=dict(family=FONT_FAMILY, size=13,
                                      color=TEXT_PRIMARY),
                            bgcolor=SURFACE, bordercolor=GRID),
            # Geo and polar subplots carry their own surfaces; without these the
            # map and radar sit on Plotly white inside a warm-white page.
            geo=dict(bgcolor=SURFACE, landcolor=SURFACE, lakecolor=SURFACE,
                     subunitcolor=GRID, countrycolor=GRID, coastlinecolor=GRID),
            polar=dict(bgcolor=SURFACE,
                       radialaxis=dict(gridcolor=GRID, linecolor=GRID),
                       angularaxis=dict(gridcolor=GRID, linecolor=GRID)),
            margin=dict(l=60, r=20, t=60, b=50),
            hovermode="x unified",
        )
    )
    pio.templates.default = TEMPLATE_NAME
